rewards:
  - "give %player% diamond 3"
  - "give %player% emerald 5"
pool:
  - oak_log
  - cobblestone
  - iron_ingot
  - carrot
  - string
  - gunpowder
  - sugar
  - bone
  - feather
  - egg
  - paper
  - leather
hopper: {}
