#execute commands, chosen randomly, unweighted sorry
rewards:
  - "give %player% diamond 3"
  - "give %player% emerald 5"
# possible scavenger hunt items (omit minecraft:) chosen randomly, unweighted sorry
pool:
  - oak_log
  - cobblestone
  - iron_ingot
  - carrot
  - string
  - gunpowder
  - sugar
  - bone
  - feather
  - egg
  - paper
  - leather
# do not touch or i'll fucking kill you
hopper: {}
